name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # "yocto_core" package settings must have "embedded_linux_dockerfiles" added as a source repository with write permissions
  build_stm32:
    env:
      ARM_URL: https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
      CMAKE_URL: https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2-linux-x86_64.tar.gz
      JLINK_URL: https://www.segger.com/downloads/jlink/JLink_Linux_x86_64.tgz
      DOCKER_TAG: 12.2.rel1
      DOCKER_IMAGE: stm32_dev:${DOCKER_TAG}
    runs-on: ubuntu-latest

    uses: ./.github/workflows/BuildTemplate.yml
    with: 
      jobName: 'build_stm32'
