name: Build

on:
  workflow_call:
    inputs:
      ARM_URL: 
        required: true
      CMAKE_URL:
        required: true
      JLINK_URL:
        required: true
      DOCKER_IMAGE:
        required: true

jobs:
  # "yocto_core" package settings must have "embedded_linux_dockerfiles" added as a source repository with write permissions
  build_stm32:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build stm32
        run: docker build --build-arg ARM_URL=${ARM_URL} --build-arg CMAKE_URL=${CMAKE_URL} --build-arg JLINK_URL=${JLINK_URL} -t ghcr.io/${{ github.actor }}/${DOCKER_IMAGE} -f ../../Dockerfile ../../
      - name: Push stm32
        run: env && docker push ghcr.io/${{ github.actor }}/${DOCKER_IMAGE}
