name: Template for Building STM32 GNU Docker Images

on:
  workflow_call:
    inputs:
      ARM_URL: 
        required: true
        type: string
      CMAKE_URL:
        required: true
        type: string
      JLINK_URL:
        required: true
        type: string
      DOCKER_IMAGE:
        required: true
        type: string

jobs:
  # "yocto_core" package settings must have "embedded_linux_dockerfiles" added as a source repository with write permissions
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build stm32
        run: docker build --build-arg ARM_URL=${{ inputs.ARM_URL }} --build-arg CMAKE_URL=${{ inputs.CMAKE_URL }} --build-arg JLINK_URL=${{ inputs.JLINK_URL }} -t ghcr.io/${{ github.actor }}/${{ inputs.DOCKER_IMAGE }} -f ./Dockerfile .
      - name: Push stm32
        run: env && docker push ghcr.io/${{ github.actor }}/${{ inputs.DOCKER_IMAGE }}
