name: Build 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # "yocto_core" package settings must have "embedded_linux_dockerfiles" added as a source repository with write permissions
  build_stm32:
    
    uses: ./.github/workflows/BuildTemplate.yml
    strategy:
      matrix:
        DOCKER_IMAGE: ["stm32_dev:10.3-2021.10", "stm32_dev:11.3.rel1", "stm32_dev:12.2.rel1"]
        ARM_URL: [
          "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2",
          "https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-eabi.tar.xz",
          "https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz"
        ]

    with:
      CMAKE_URL: https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2-linux-x86_64.tar.gz
      JLINK_URL: https://www.segger.com/downloads/jlink/JLink_Linux_x86_64.tgz
    


